from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 800)
        self.graphicsView_17 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_17.setGeometry(QtCore.QRect(300, 60, 100, 100))
        self.graphicsView_17.setObjectName("graphicsView_17")
        self.dice_pushButton = QtWidgets.QPushButton(Dialog)
        self.dice_pushButton.setGeometry(QtCore.QRect(570, 240, 75, 41))
        self.dice_pushButton.setObjectName("dice_pushButton")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(510, 320, 201, 91))
        self.textEdit.setObjectName("textEdit")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(0, 600, 250, 200))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(950, 600, 250, 200))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.graphicsView_19 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_19.setGeometry(QtCore.QRect(400, 60, 100, 100))
        self.graphicsView_19.setObjectName("graphicsView_19")
        self.graphicsView_20 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_20.setGeometry(QtCore.QRect(600, 60, 100, 100))
        self.graphicsView_20.setObjectName("graphicsView_20")
        self.graphicsView_21 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_21.setGeometry(QtCore.QRect(500, 60, 100, 100))
        self.graphicsView_21.setObjectName("graphicsView_21")
        self.graphicsView_22 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_22.setGeometry(QtCore.QRect(700, 60, 100, 100))
        self.graphicsView_22.setObjectName("graphicsView_22")
        self.graphicsView_18 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_18.setGeometry(QtCore.QRect(300, 160, 100, 100))
        self.graphicsView_18.setObjectName("graphicsView_18")
        self.graphicsView_23 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_23.setGeometry(QtCore.QRect(300, 260, 100, 100))
        self.graphicsView_23.setObjectName("graphicsView_23")
        self.graphicsView_24 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_24.setGeometry(QtCore.QRect(300, 360, 100, 100))
        self.graphicsView_24.setObjectName("graphicsView_24")
        self.graphicsView_25 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_25.setGeometry(QtCore.QRect(300, 460, 100, 100))
        self.graphicsView_25.setObjectName("graphicsView_25")
        self.graphicsView_26 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_26.setGeometry(QtCore.QRect(500, 460, 100, 100))
        self.graphicsView_26.setObjectName("graphicsView_26")
        self.graphicsView_27 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_27.setGeometry(QtCore.QRect(400, 460, 100, 100))
        self.graphicsView_27.setObjectName("graphicsView_27")
        self.graphicsView_28 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_28.setGeometry(QtCore.QRect(600, 460, 100, 100))
        self.graphicsView_28.setObjectName("graphicsView_28")
        self.graphicsView_29 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_29.setGeometry(QtCore.QRect(700, 460, 100, 100))
        self.graphicsView_29.setObjectName("graphicsView_29")
        self.graphicsView_30 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_30.setGeometry(QtCore.QRect(800, 460, 100, 100))
        self.graphicsView_30.setObjectName("graphicsView_30")
        self.graphicsView_31 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_31.setGeometry(QtCore.QRect(800, 60, 100, 100))
        self.graphicsView_31.setObjectName("graphicsView_31")
        self.graphicsView_32 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_32.setGeometry(QtCore.QRect(800, 160, 100, 100))
        self.graphicsView_32.setObjectName("graphicsView_32")
        self.graphicsView_33 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_33.setGeometry(QtCore.QRect(800, 360, 100, 100))
        self.graphicsView_33.setObjectName("graphicsView_33")
        self.graphicsView_34 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_34.setGeometry(QtCore.QRect(800, 260, 100, 100))
        self.graphicsView_34.setObjectName("graphicsView_34")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.dice_pushButton.setText(_translate("Dialog", "Dice"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">무인도!~!</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
